version: '3.8'

services:
  db:
    image: postgres:16.3-bullseye
    environment:
      POSTGRES_PASSWORD: olast
      POSTGRES_USER: olast
      POSTGRES_DB: olast
    volumes:
      - ./pgsql:/var/lib/postgresql/data
      - ./app/migrations/deploy/01-data-base-initialisation.sql:/docker-entrypoint-initdb.d/01-data-base-initialisation.sql
    expose:
      - 5432
    ports:
      - 5433:5432

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      PGUSER: olast
      PGPASSWORD: olast
      PGDATABASE: olast
      PGHOST: db
      PGPORT: 5432

volumes:
  pgdata:
