version: '3.8'

services:
  db:
    image: postgres:16.3-bullseye
    environment:
      POSTGRES_PASSWORD: olast
      POSTGRES_USER: olast
      POSTGRES_DB: olast
    volumes:
      - ./pgsql:/var/lib/postgresql/data
      - ./app/data/migrations/deploy/01-data-base-initialisation.sql:/docker-entrypoint-initdb.d/01-data-base-initialisation.sql
      - ./app/data/seeding.sql:/docker-entrypoint-initdb.d/seeding.sql
    expose:
      - 5432
    ports:
      - "5433:5432"

  app:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      PG_URL: postgres://olast:olast@db:5433/olast
      PG_PORT: 5433
    env_file:
      - .env
    volumes:
      - .:/app

volumes:
  pgdata:
